'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Eye, Plus, Trash2 } from 'lucide-react';
import AuthGuard from '@/components/AuthGuard';
import StatusBadge from '@/components/StatusBadge';
import { useAuth } from '@/context/AuthContext';
import { deletePartnerExperience, getMyExperiences } from '@/lib/partner-firestore';
import { Experience } from '@/types';
function Content(){const{appUser}=useAuth();const[items,setItems]=useState<Experience[]>([]);const[loading,setLoading]=useState(true);async function load(){if(appUser)setItems(await getMyExperiences(appUser.uid))}useEffect(()=>{load().finally(()=>setLoading(false))},[appUser]);if(loading)return <div className="py-20 text-center">Chargement…</div>;return <div><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-solar">Produit principal</p><h1 className="mt-1 font-display text-4xl font-bold">Mes expériences</h1><p className="mt-2 text-gray-500">{items.length} expérience{items.length>1?'s':''} publiée{items.length>1?'s':''} ou en validation.</p></div><Link href="/partner/create-experience" className="inline-flex items-center gap-2 rounded-2xl bg-solar px-5 py-3 font-bold text-white"><Plus size={17}/>Publier une expérience</Link></div>{!items.length?<div className="rounded-[2rem] bg-white py-20 text-center shadow-card"><div className="text-5xl">✨</div><h2 className="mt-4 font-display text-xl font-bold">Ta première expérience commence ici</h2><p className="mt-2 text-gray-500">Présente ce que les visiteurs pourront réellement vivre.</p><Link href="/partner/create-experience" className="mt-6 inline-flex rounded-2xl bg-solar px-6 py-3 font-bold text-white">Créer mon expérience</Link></div>:<div className="space-y-4">{items.map(x=><article key={x.id} className="flex flex-col gap-5 rounded-3xl bg-white p-5 shadow-card sm:flex-row">{x.images[0]?<img src={x.images[0]} alt={x.title} className="h-32 w-full rounded-2xl object-cover sm:w-44"/>:<div className="grid h-32 w-full place-items-center rounded-2xl bg-orange-50 text-3xl sm:w-44">✨</div>}<div className="flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-solar">{x.category}</p><h2 className="font-display text-xl font-bold">{x.title}</h2><p className="mt-1 text-sm text-gray-500">{x.city}{x.district?` · ${x.district}`:''}</p></div><StatusBadge status={x.status??'pending'}/></div><p className="mt-3 line-clamp-2 text-sm text-gray-600">{x.description}</p>{x.moderationNote&&x.status==='rejected'&&<p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">Motif : {x.moderationNote}</p>}<div className="mt-4 flex items-center justify-between"><span className="inline-flex items-center gap-1 text-xs text-gray-400"><Eye size={13}/>{x.views??0} vues</span><button onClick={async()=>{if(confirm('Supprimer cette expérience ?')){await deletePartnerExperience(x.id);load()}}} className="inline-flex items-center gap-1 text-sm font-semibold text-red-500"><Trash2 size={14}/>Supprimer</button></div></div></article>)}</div>}</div>}
export default function Page(){return <main className="site-container py-10"><AuthGuard partnerOnly><Content/></AuthGuard></main>}
