'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2, ExternalLink, Search, ShieldCheck, XCircle } from 'lucide-react';
import AuthGuard from '@/components/AuthGuard';
import { useAuth } from '@/context/AuthContext';
import { CreatorVerificationRequest, CreatorVerificationStatus } from '@/types';
import { listVerificationRequests, reviewVerificationRequest } from '@/lib/trust-safety-firestore';

export default function Page(){const {appUser}=useAuth();const [items,setItems]=useState<CreatorVerificationRequest[]>([]);const [selected,setSelected]=useState<CreatorVerificationRequest|null>(null);const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [note,setNote]=useState('');const load=()=>listVerificationRequests().then(setItems);useEffect(()=>{load()},[]);const visible=useMemo(()=>items.filter(i=>(filter==='all'||i.status===filter)&&(`${i.creatorDisplayName} ${i.legalName} ${i.creatorEmail}`.toLowerCase().includes(search.toLowerCase()))),[items,filter,search]);async function decide(status:Exclude<CreatorVerificationStatus,'draft'|'pending'>){if(!selected||!appUser)return;await reviewVerificationRequest(selected,status,note,appUser.uid);setSelected(null);setNote('');load()}
return <main className="site-container py-10"><AuthGuard adminOnly><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-gray-500"><ArrowLeft size={16}/> Administration</Link><header className="mt-6 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-solar">Trust & Safety</p><h1 className="mt-1 font-display text-4xl font-bold">Demandes de vérification</h1><p className="mt-2 text-gray-500">Contrôler les dossiers Créateurs et attribuer les statuts de confiance.</p></div></header><div className="mt-7 flex flex-col gap-3 md:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-gray-200 px-4"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher" className="w-full py-3 outline-none"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-gray-200 px-4 py-3"><option value="all">Tous les statuts</option><option value="pending">En attente</option><option value="needs_information">Complément demandé</option><option value="approved">Vérifié</option><option value="rejected">Refusé</option><option value="partner">Partenaire</option></select></div><div className="mt-6 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="divide-y divide-gray-100">{visible.map(i=><button key={i.id} onClick={()=>{setSelected(i);setNote(i.adminNote||'')}} className="flex w-full items-center justify-between gap-4 p-5 text-left hover:bg-orange-50"><div><strong>{i.creatorDisplayName||i.legalName}</strong><p className="mt-1 text-xs text-gray-500">{i.creatorEmail} · {i.professionalPhone}</p></div><Status status={i.status}/></button>)}{visible.length===0&&<p className="p-10 text-center text-gray-400">Aucune demande.</p>}</div></div>
{selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 p-0 md:items-center md:p-6"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-white p-6 md:rounded-3xl md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-solar">Dossier Créateur</p><h2 className="mt-1 font-display text-3xl font-bold">{selected.legalName}</h2></div><button onClick={()=>setSelected(null)}><XCircle/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Info k="Nom commercial" v={selected.commercialName}/><Info k="RCCM" v={selected.rccm}/><Info k="Compte contribuable" v={selected.taxpayerNumber}/><Info k="Téléphone" v={selected.professionalPhone}/><Info k="Email" v={selected.professionalEmail}/><Info k="Adresse" v={selected.professionalAddress}/></div><div className="mt-6 grid gap-3 md:grid-cols-2">{[selected.identityFront,selected.identityBack,selected.rccmDocument,selected.taxpayerDocument].filter(Boolean).map((d:any)=><a key={d.label} href={d.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-gray-200 p-4 font-semibold hover:border-solar">{d.label}<ExternalLink size={16}/></a>)}</div><label className="mt-6 block text-sm font-semibold">Note administrative<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-gray-200 p-4"/></label><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><button onClick={()=>decide('needs_information')} className="rounded-xl border px-4 py-3 font-bold">Demander un complément</button><button onClick={()=>decide('rejected')} className="rounded-xl bg-red-50 px-4 py-3 font-bold text-red-700">Refuser</button><button onClick={()=>decide('approved')} className="rounded-xl bg-green-50 px-4 py-3 font-bold text-green-700">Vérifier</button><button onClick={()=>decide('partner')} className="rounded-xl bg-anthracite px-4 py-3 font-bold text-white">Partenaire KIFFCI</button></div></div></div>}</AuthGuard></main>}
function Info({k,v}:{k:string;v?:string}){return <div className="rounded-xl bg-gray-50 p-4"><p className="text-xs uppercase text-gray-400">{k}</p><p className="mt-1 font-semibold">{v||'—'}</p></div>}
function Status({status}:{status:CreatorVerificationStatus}){const m:any={draft:'Brouillon',pending:'En attente',needs_information:'Complément',approved:'Vérifié',rejected:'Refusé',partner:'Partenaire'};return <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold">{m[status]}</span>}
